version: "3"
services:
  nginx:
    image: nginx:1.17.3
    ports:
      - "80"

  nginx-waf:
    build:
      context: .
    volumes:
      - ./tests/nginx-conf.d:/etc/nginx/conf.d
    ports:
      - "8080"
      - "8081"

  sut:
    build:
      context: ./tests
      dockerfile: Dockerfile
    depends_on:
      - nginx
      - nginx-waf

